/**
 * Test Example for Aria Runtime
 *
 * This is a simple test program that simulates what compiled Aria code
 * would look like. It demonstrates all the runtime functions.
 *
 * Compile and link:
 *   gcc -c aria_runtime.c -o aria_runtime.o
 *   gcc -c test_example.c -o test_example.o
 *   gcc aria_runtime.o test_example.o -o test_example
 *
 * Or use the build script:
 *   ./build.sh build
 *   gcc aria_runtime.o test_example.o -o test_example
 */

#include "aria_runtime.h"

/**
 * This is the Aria program's main function.
 * In a real compiled Aria program, this would be generated by the compiler.
 */
void aria_main(void) {
    // Print various types
    aria_print_string("Hello from Aria!");
    aria_print_newline();

    aria_print_string("Integer: ");
    aria_print_int(42);
    aria_print_newline();

    aria_print_string("Float: ");
    aria_print_float(3.14159);
    aria_print_newline();

    aria_print_string("Boolean: ");
    aria_print_bool(1);
    aria_print_newline();

    aria_print_string("Boolean: ");
    aria_print_bool(0);
    aria_print_newline();

    // Test string operations
    aria_print_newline();
    aria_print_string("=== String Operations ===");
    aria_print_newline();

    const char* str1 = "Hello, ";
    const char* str2 = "World!";

    char* concat = aria_string_concat(str1, str2);
    aria_print_string("Concatenated: ");
    aria_print_string(concat);
    aria_print_newline();

    aria_print_string("Strings equal? ");
    aria_print_bool(aria_string_eq(str1, str2));
    aria_print_newline();

    aria_print_string("Strings equal? ");
    aria_print_bool(aria_string_eq(str1, "Hello, "));
    aria_print_newline();

    // Clean up allocated string
    aria_dealloc(concat, 0);

    // Test memory allocation
    aria_print_newline();
    aria_print_string("=== Memory Allocation ===");
    aria_print_newline();

    void* mem = aria_alloc(1024);
    aria_print_string("Allocated 1024 bytes");
    aria_print_newline();
    aria_dealloc(mem, 1024);
    aria_print_string("Freed memory");
    aria_print_newline();

    // Success message
    aria_print_newline();
    aria_print_string("All tests completed successfully!");
    aria_print_newline();

    // Uncomment to test panic:
    // aria_panic("This is a test panic");
}
