//! # Aria FFI
//!
//! Foreign Function Interface support for the Aria programming language.
//!
//! This crate provides:
//! - C type mappings (`CInt`, `CUInt`, `CString`, `CVoidPtr`, etc.)
//! - FFI safety markers (`Owned`, `Borrowed`, `Transfer` annotations)
//! - Pointer types (`CPtr<T>`, `CArray<T, N>`)
//! - FFI error types
//! - C header parsing for automatic binding generation
//!
//! ## Design Philosophy
//!
//! Aria's FFI is designed with safety as the default:
//! - Safe wrappers are generated by default with bounds checking
//! - Explicit `unsafe` blocks for direct FFI access
//! - Ownership annotations (`@owned`, `@borrowed`, `@transfer`) at boundaries
//!
//! Based on ARIA-PD-010: FFI and Foreign Interoperability Design
//! and ARIA-M09: C Interop System

pub mod c_header_parser;
pub mod c_types;
pub mod error;
pub mod ownership;
pub mod pointer;

// Re-export main types for convenience
pub use c_header_parser::{
    AriaFfiType, CConstantDecl, CConstantValue, CDeclaration, CEnumDecl, CFunctionDecl,
    CHeaderParser, CStructDecl, CType, CTypedefDecl, SafeWrapper,
};
pub use c_types::*;
pub use error::{FfiError, FfiResult};
pub use ownership::{Borrowed, Owned, Transfer};
pub use pointer::{CArray, CPtr};
